name: uj_ui
description: "Umbijani UI Component package."
repository: https://github.com/mwangaben/uj_ui
issue_tracker: https://github.com/mwangaben/uj_ui/issues

version: 0.0.5

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  searchfield: 1.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


